package com.example.toollibs.Activity.DataBase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.toollibs.Activity.Bean.Books;
import com.example.toollibs.Activity.Bean.Students;

import com.example.toollibs.Activity.DataBase.BooksDao;
import com.example.toollibs.Activity.DataBase.StudentsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig booksDaoConfig;
    private final DaoConfig studentsDaoConfig;

    private final BooksDao booksDao;
    private final StudentsDao studentsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        booksDaoConfig = daoConfigMap.get(BooksDao.class).clone();
        booksDaoConfig.initIdentityScope(type);

        studentsDaoConfig = daoConfigMap.get(StudentsDao.class).clone();
        studentsDaoConfig.initIdentityScope(type);

        booksDao = new BooksDao(booksDaoConfig, this);
        studentsDao = new StudentsDao(studentsDaoConfig, this);

        registerDao(Books.class, booksDao);
        registerDao(Students.class, studentsDao);
    }
    
    public void clear() {
        booksDaoConfig.clearIdentityScope();
        studentsDaoConfig.clearIdentityScope();
    }

    public BooksDao getBooksDao() {
        return booksDao;
    }

    public StudentsDao getStudentsDao() {
        return studentsDao;
    }

}
