package com.example.toollibs.Activity.DataBase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.toollibs.Activity.Bean.Students;
import com.example.toollibs.Activity.Bean.Books;

import com.example.toollibs.Activity.DataBase.StudentsDao;
import com.example.toollibs.Activity.DataBase.BooksDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentsDaoConfig;
    private final DaoConfig booksDaoConfig;

    private final StudentsDao studentsDao;
    private final BooksDao booksDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentsDaoConfig = daoConfigMap.get(StudentsDao.class).clone();
        studentsDaoConfig.initIdentityScope(type);

        booksDaoConfig = daoConfigMap.get(BooksDao.class).clone();
        booksDaoConfig.initIdentityScope(type);

        studentsDao = new StudentsDao(studentsDaoConfig, this);
        booksDao = new BooksDao(booksDaoConfig, this);

        registerDao(Students.class, studentsDao);
        registerDao(Books.class, booksDao);
    }
    
    public void clear() {
        studentsDaoConfig.clearIdentityScope();
        booksDaoConfig.clearIdentityScope();
    }

    public StudentsDao getStudentsDao() {
        return studentsDao;
    }

    public BooksDao getBooksDao() {
        return booksDao;
    }

}
